### ISSUE TITLE
No Expenses Tab

### ISSUE THREAD

**Issue by jamesward** [pchittum/lightning-app-builder-tutorial#1]
https://pchittum.github.io/lightning-app-builder-tutorial/Importing-Workshop-Assets.html

Didn't have an Expenses Tab

**Comment by pchittum** [comment]
Hey James,

Was it non-existent, or could it be found in the "+" tab?

Peter Chittum
Developer Relations
Salesforce EMEA
+44 7786 515 531
pchittum@salesforce.com
@pchittum

On Wed, Feb 11, 2015 at 4:23 PM, James Ward <notifications@github.com>
wrote:

>
> https://pchittum.github.io/lightning-app-builder-tutorial/Importing-Workshop-Assets.html
>
> Didn't have an Expenses Tab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pchittum/lightning-app-builder-tutorial/issues/1>.
>

-- 



salesforce.com EMEA Limited, registered in England and Wales under company 
number 05094083, with registered address Floor 26 Salesforce Tower, 110 
Bishopsgate, London EC2N 4AY, UK.

**Comment by pchittum** [comment]
sorry...i should do as I ask...

Peter Chittum
Developer Relations
Salesforce EMEA
+44 7786 515 531
pchittum@salesforce.com
@pchittum

On Wed, Feb 11, 2015 at 5:20 PM, Peter Chittum <pchittum@salesforce.com>
wrote:

> Hey James,
>
> Was it non-existent, or could it be found in the "+" tab?
>
> Peter Chittum
> Developer Relations
> Salesforce EMEA
> +44 7786 515 531
> pchittum@salesforce.com
> @pchittum
>
> On Wed, Feb 11, 2015 at 4:23 PM, James Ward <notifications@github.com>
> wrote:
>
>>
>> https://pchittum.github.io/lightning-app-builder-tutorial/Importing-Workshop-Assets.html
>>
>> Didn't have an Expenses Tab
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pchittum/lightning-app-builder-tutorial/issues/1>.
>>
>
>

-- 



salesforce.com EMEA Limited, registered in England and Wales under company 
number 05094083, with registered address Floor 26 Salesforce Tower, 110 
Bishopsgate, London EC2N 4AY, UK.

**Comment by jamesward** [comment]
Non-existent.

**Comment by pchittum** [comment]
Ok. For now, go to your user and assign yourself the two permission sets. You should see it then, either as a tab itself, or in the + tab.

**Comment by jr0cket** [comment]
I added the two permission sets as Mr Chittum suggested, but still no sign of the expenses tab :-1:

**Comment by jr0cket** [comment]
Mr Chittum has created a new package that contains the Expenses tab at:

https://login.salesforce.com/packaging/installPackage.apexp?p0=04tB00000001BEw

Fixed in #8

**Comment by pchittum** [comment]
Fixed package. New package URL is as stated with John's comment above. Have accepted pull request with updated url in the page.
